---
- name: Deploy Ubuntu
  hosts: localhost
  gather_facts: no
  vars:
    pip_package_requirements:
      - "requests"
      - "pyVim"
      - "pyVmomi"
  tasks:
    - name: Install pip requests library
      pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ pip_package_requirements }}"
    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
      delegate_to: localhost
      register: vminfo
    - name: Generate id for the new clone
      ansible.builtin.set_fact:
        clone_id: "{{ vminfo.virtual_machines | length }}"
    - debug:
        msg: |
          [
            "vminfo length: {{ clone_id + 1 }}",
            "vminfo: {{ vminfo.virtual_machines }}",
          ]
        register: vmNBR
    - name: Clone a virtual machine from Linux template and customize
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: "/"
        cluster: "Nouveau cluster"
        datacenter: "Datacenter"
        state: present
        template: "Ubuntu-Desktop-Template"
        name: "Client_{{ clone_id + 1 }}"
        networks:
          - name: "DPortGroup 1"
            start_connected: True
            type: dhcp
        wait_for_ip_address: true
        wait_for_customization: true
        customization:
          domain: "projet.si"
          dns_servers:
            - 10.0.0.10
          script_text: |  
            #!/bin/bash
            touch /tmp/touch-from-playbook
            echo "Hostname=$HOSTNAME" >> /etc/zabbix/zabbix_agentd.conf
            sudo systemctl restart zabbix-agent
      delegate_to: localhost
