---
- name: Deploy Windows
  hosts: localhost
  gather_facts: no
  vars:
    pip_package_requirements:
      - "requests"
      - "pyVim"
      - "pyVmomi"
  tasks:
    - name: Install pip requests library
      delegate_to: localhost
      pip:
        name: "{{ item }}"
        state: present

      with_items: "{{ pip_package_requirements }}"
    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
      delegate_to: localhost
      register: vminfo
    - debug:
        msg: |
          [
            "vminfo length: {{ vminfo.virtual_machines | length + 1 }}",
          ]
    - name: Clone a virtual machine from Windows template and customize
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: "/"
        cluster: "Nouveau cluster 1"
        datacenter: "Datacenter"
        state: present
        template: "-Template"
        name: "Client{{ vminfo.virtual_machines | length + 1 }}"
        networks:
          - name: "DPortGroup 1"
            start_connected: True
            type: dhcp
        wait_for_ip_address: true
        wait_for_customization: true
        customization:
          domain: "projet.si"
          dns_servers:
            - 10.0.0.10
          runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Users\user\Desktop\installer.ps1 -ForceNewSSLCert -EnableCredSSP
      delegate_to: localhost