---
- name: Deploy Ubuntu
  hosts: localhost
  gather_facts: no
  vars:
    pip_package_requirements:
      - "requests"
      - "pyVim"
      - "pyVmomi"
  tasks:
    - name: Install pip requests library
      pip:
          name: "{{ item }}"
          state: present
      with_items: "{{ pip_package_requirements }}"
    - name: Instant Clone a VM with guest_customization
      community.vmware.vmware_guest_instant_clone:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        vm_username: "ubuntu"
        vm_password: "Test1234$"
        validate_certs: false
        datastore: "datastore1 (ESXI2)"
        datacenter: "Datacenter"
        host: "10.75.255.214"
        guestinfo_vars:
          - hostname: "{{ guestinfo.hostname }}"
        name: "Instant_clone_guest_customize"
        parent_vm: "Ubuntu-Server-Template"
      register: Instant_cloned_guest_customize
      delegate_to: localhost