---
- name: Deploy Ubuntu
  hosts: localhost
  gather_facts: no
  vars:
    pip_package_requirements:
      - "requests"
      - "pyVim"
      - "pyVmomi"
  tasks:
    - name: Clone a virtual machine from Linux template and customize
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: "/"
        cluster: "Nouveau cluster"
        datacenter: "Datacenter"
        state: present
        template: "Ubuntu-Desktop-Template"
        name: "{{ vm_name }}"
        networks:
          - name: "DPortGroup 1"
            start_connected: True
            type: dhcp
        wait_for_ip_address: true
        wait_for_customization: true
        customization:
          domain: "projet.si"
          dns_servers:
            - 10.0.0.10
          script_text: |  
            #!/bin/bash
            touch /tmp/touch-from-playbook
            echo "Hostname=$HOSTNAME" >> /etc/zabbix/zabbix_agentd.conf
            sudo systemctl restart zabbix-agent
      delegate_to: localhost
