---
- name: Update all Windows
  hosts: all
  gather_facts: no
  vars:
    pip_package_requirements:
      - "requests"
      - "pyVim"
      - "pyVmomi"
      - "pywinrm"
  tasks:
    - name: Install pip requests library
      delegate_to: localhost
      pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ pip_package_requirements }}"
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        validate_certs: false
        category_names: '*'
        reboot: yes