---
- name: Update all Windows
  hosts: localhost
  gather_facts: no
  vars:
    pip_package_requirements:
  tasks:
    - name: Install pip requests library
      delegate_to: localhost
      pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ pip_package_requirements }}"
    - name: Install all updates and reboot as many times as needed
      delegate_to: localhost
      shell: |
        "echo azer"
      register: os_info